// Code generated by internal/gen from the macOS SDK; DO NOT EDIT.

//go:build darwin

package security

const (

	// Class Key Constant
	Class Key = "kSecClass"

	// Class Value Constants
	ClassInternetPassword Constant = "kSecClassInternetPassword"
	ClassGenericPassword  Constant = "kSecClassGenericPassword"
	ClassCertificate      Constant = "kSecClassCertificate"
	ClassKey              Constant = "kSecClassKey"
	ClassIdentity         Constant = "kSecClassIdentity"

	// Attribute Key Constants
	AttrAccessible          Key      = "kSecAttrAccessible"
	AttrAccess              Key      = "kSecAttrAccess"
	AttrAccessControl       Key      = "kSecAttrAccessControl"
	AttrAccessGroup         Key      = "kSecAttrAccessGroup"
	AttrSynchronizable      Key      = "kSecAttrSynchronizable"
	AttrSynchronizableAny   Constant = "kSecAttrSynchronizableAny"
	AttrCreationDate        Key      = "kSecAttrCreationDate"
	AttrModificationDate    Key      = "kSecAttrModificationDate"
	AttrDescription         Key      = "kSecAttrDescription"
	AttrComment             Key      = "kSecAttrComment"
	AttrCreator             Key      = "kSecAttrCreator"
	AttrType                Key      = "kSecAttrType"
	AttrLabel               Key      = "kSecAttrLabel"
	AttrIsInvisible         Key      = "kSecAttrIsInvisible"
	AttrIsNegative          Key      = "kSecAttrIsNegative"
	AttrAccount             Key      = "kSecAttrAccount"
	AttrService             Key      = "kSecAttrService"
	AttrGeneric             Key      = "kSecAttrGeneric"
	AttrSecurityDomain      Key      = "kSecAttrSecurityDomain"
	AttrServer              Key      = "kSecAttrServer"
	AttrProtocol            Key      = "kSecAttrProtocol"
	AttrAuthenticationType  Key      = "kSecAttrAuthenticationType"
	AttrPort                Key      = "kSecAttrPort"
	AttrPath                Key      = "kSecAttrPath"
	AttrSubject             Key      = "kSecAttrSubject"
	AttrIssuer              Key      = "kSecAttrIssuer"
	AttrSerialNumber        Key      = "kSecAttrSerialNumber"
	AttrSubjectKeyID        Key      = "kSecAttrSubjectKeyID"
	AttrPublicKeyHash       Key      = "kSecAttrPublicKeyHash"
	AttrCertificateType     Key      = "kSecAttrCertificateType"
	AttrCertificateEncoding Key      = "kSecAttrCertificateEncoding"
	AttrKeyClass            Key      = "kSecAttrKeyClass"
	AttrApplicationLabel    Key      = "kSecAttrApplicationLabel"
	AttrIsPermanent         Key      = "kSecAttrIsPermanent"
	AttrIsSensitive         Key      = "kSecAttrIsSensitive"
	AttrIsExtractable       Key      = "kSecAttrIsExtractable"
	AttrApplicationTag      Key      = "kSecAttrApplicationTag"
	AttrKeyType             Key      = "kSecAttrKeyType"
	AttrPRF                 Key      = "kSecAttrPRF"
	AttrSalt                Key      = "kSecAttrSalt"
	AttrRounds              Key      = "kSecAttrRounds"
	AttrKeySizeInBits       Key      = "kSecAttrKeySizeInBits"
	AttrEffectiveKeySize    Key      = "kSecAttrEffectiveKeySize"
	AttrCanEncrypt          Key      = "kSecAttrCanEncrypt"
	AttrCanDecrypt          Key      = "kSecAttrCanDecrypt"
	AttrCanDerive           Key      = "kSecAttrCanDerive"
	AttrCanSign             Key      = "kSecAttrCanSign"
	AttrCanVerify           Key      = "kSecAttrCanVerify"
	AttrCanWrap             Key      = "kSecAttrCanWrap"
	AttrCanUnwrap           Key      = "kSecAttrCanUnwrap"
	AttrSyncViewHint        Key      = "kSecAttrSyncViewHint"
	AttrTokenID             Key      = "kSecAttrTokenID"
	AttrPersistantReference Key      = "kSecAttrPersistantReference"
	AttrPersistentReference Key      = "kSecAttrPersistentReference"

	// kSecAttrAccessible Value Constants
	AttrAccessibleWhenUnlocked     Constant = "kSecAttrAccessibleWhenUnlocked"
	AttrAccessibleAfterFirstUnlock Constant = "kSecAttrAccessibleAfterFirstUnlock"

	// AttrAccessibleAlways is kSecAttrAccessibleAlways.
	//
	// Deprecated: Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlock
	AttrAccessibleAlways Constant = "kSecAttrAccessibleAlways"

	AttrAccessibleWhenPasscodeSetThisDeviceOnly  Constant = "kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly"
	AttrAccessibleWhenUnlockedThisDeviceOnly     Constant = "kSecAttrAccessibleWhenUnlockedThisDeviceOnly"
	AttrAccessibleAfterFirstUnlockThisDeviceOnly Constant = "kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly"

	// AttrAccessibleAlwaysThisDeviceOnly is kSecAttrAccessibleAlwaysThisDeviceOnly.
	//
	// Deprecated: Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
	AttrAccessibleAlwaysThisDeviceOnly Constant = "kSecAttrAccessibleAlwaysThisDeviceOnly"

	// kSecAttrProtocol Value Constants
	AttrProtocolFTP        Constant = "kSecAttrProtocolFTP"
	AttrProtocolFTPAccount Constant = "kSecAttrProtocolFTPAccount"
	AttrProtocolHTTP       Constant = "kSecAttrProtocolHTTP"
	AttrProtocolIRC        Constant = "kSecAttrProtocolIRC"
	AttrProtocolNNTP       Constant = "kSecAttrProtocolNNTP"
	AttrProtocolPOP3       Constant = "kSecAttrProtocolPOP3"
	AttrProtocolSMTP       Constant = "kSecAttrProtocolSMTP"
	AttrProtocolSOCKS      Constant = "kSecAttrProtocolSOCKS"
	AttrProtocolIMAP       Constant = "kSecAttrProtocolIMAP"
	AttrProtocolLDAP       Constant = "kSecAttrProtocolLDAP"
	AttrProtocolAppleTalk  Constant = "kSecAttrProtocolAppleTalk"
	AttrProtocolAFP        Constant = "kSecAttrProtocolAFP"
	AttrProtocolTelnet     Constant = "kSecAttrProtocolTelnet"
	AttrProtocolSSH        Constant = "kSecAttrProtocolSSH"
	AttrProtocolFTPS       Constant = "kSecAttrProtocolFTPS"
	AttrProtocolHTTPS      Constant = "kSecAttrProtocolHTTPS"
	AttrProtocolHTTPProxy  Constant = "kSecAttrProtocolHTTPProxy"
	AttrProtocolHTTPSProxy Constant = "kSecAttrProtocolHTTPSProxy"
	AttrProtocolFTPProxy   Constant = "kSecAttrProtocolFTPProxy"
	AttrProtocolSMB        Constant = "kSecAttrProtocolSMB"
	AttrProtocolRTSP       Constant = "kSecAttrProtocolRTSP"
	AttrProtocolRTSPProxy  Constant = "kSecAttrProtocolRTSPProxy"
	AttrProtocolDAAP       Constant = "kSecAttrProtocolDAAP"
	AttrProtocolEPPC       Constant = "kSecAttrProtocolEPPC"
	AttrProtocolIPP        Constant = "kSecAttrProtocolIPP"
	AttrProtocolNNTPS      Constant = "kSecAttrProtocolNNTPS"
	AttrProtocolLDAPS      Constant = "kSecAttrProtocolLDAPS"
	AttrProtocolTelnetS    Constant = "kSecAttrProtocolTelnetS"
	AttrProtocolIMAPS      Constant = "kSecAttrProtocolIMAPS"
	AttrProtocolIRCS       Constant = "kSecAttrProtocolIRCS"
	AttrProtocolPOP3S      Constant = "kSecAttrProtocolPOP3S"

	// kSecAttrAuthenticationType Value Constants
	AttrAuthenticationTypeNTLM       Constant = "kSecAttrAuthenticationTypeNTLM"
	AttrAuthenticationTypeMSN        Constant = "kSecAttrAuthenticationTypeMSN"
	AttrAuthenticationTypeDPA        Constant = "kSecAttrAuthenticationTypeDPA"
	AttrAuthenticationTypeRPA        Constant = "kSecAttrAuthenticationTypeRPA"
	AttrAuthenticationTypeHTTPBasic  Constant = "kSecAttrAuthenticationTypeHTTPBasic"
	AttrAuthenticationTypeHTTPDigest Constant = "kSecAttrAuthenticationTypeHTTPDigest"
	AttrAuthenticationTypeHTMLForm   Constant = "kSecAttrAuthenticationTypeHTMLForm"
	AttrAuthenticationTypeDefault    Constant = "kSecAttrAuthenticationTypeDefault"

	// kSecAttrKeyClass Value Constants
	AttrKeyClassPublic    Constant = "kSecAttrKeyClassPublic"
	AttrKeyClassPrivate   Constant = "kSecAttrKeyClassPrivate"
	AttrKeyClassSymmetric Constant = "kSecAttrKeyClassSymmetric"

	// kSecAttrKeyType Value Constants
	AttrKeyTypeRSA              Constant = "kSecAttrKeyTypeRSA"
	AttrKeyTypeDSA              Constant = "kSecAttrKeyTypeDSA"
	AttrKeyTypeAES              Constant = "kSecAttrKeyTypeAES"
	AttrKeyTypeDES              Constant = "kSecAttrKeyTypeDES"
	AttrKeyType3DES             Constant = "kSecAttrKeyType3DES"
	AttrKeyTypeRC4              Constant = "kSecAttrKeyTypeRC4"
	AttrKeyTypeRC2              Constant = "kSecAttrKeyTypeRC2"
	AttrKeyTypeCAST             Constant = "kSecAttrKeyTypeCAST"
	AttrKeyTypeECDSA            Constant = "kSecAttrKeyTypeECDSA"
	AttrKeyTypeEC               Constant = "kSecAttrKeyTypeEC"
	AttrKeyTypeECSECPrimeRandom Constant = "kSecAttrKeyTypeECSECPrimeRandom"

	// kSecAttrPRF Value Constants
	AttrPRFHmacAlgSHA1   Constant = "kSecAttrPRFHmacAlgSHA1"
	AttrPRFHmacAlgSHA224 Constant = "kSecAttrPRFHmacAlgSHA224"
	AttrPRFHmacAlgSHA256 Constant = "kSecAttrPRFHmacAlgSHA256"
	AttrPRFHmacAlgSHA384 Constant = "kSecAttrPRFHmacAlgSHA384"
	AttrPRFHmacAlgSHA512 Constant = "kSecAttrPRFHmacAlgSHA512"

	// Search Constants
	MatchPolicy                Key      = "kSecMatchPolicy"
	MatchItemList              Key      = "kSecMatchItemList"
	MatchSearchList            Key      = "kSecMatchSearchList"
	MatchIssuers               Key      = "kSecMatchIssuers"
	MatchEmailAddressIfPresent Key      = "kSecMatchEmailAddressIfPresent"
	MatchSubjectContains       Key      = "kSecMatchSubjectContains"
	MatchHostOrSubdomainOfHost Key      = "kSecMatchHostOrSubdomainOfHost"
	MatchSubjectStartsWith     Key      = "kSecMatchSubjectStartsWith"
	MatchSubjectEndsWith       Key      = "kSecMatchSubjectEndsWith"
	MatchSubjectWholeString    Key      = "kSecMatchSubjectWholeString"
	MatchCaseInsensitive       Key      = "kSecMatchCaseInsensitive"
	MatchDiacriticInsensitive  Key      = "kSecMatchDiacriticInsensitive"
	MatchWidthInsensitive      Key      = "kSecMatchWidthInsensitive"
	MatchTrustedOnly           Key      = "kSecMatchTrustedOnly"
	MatchValidOnDate           Key      = "kSecMatchValidOnDate"
	MatchLimit                 Key      = "kSecMatchLimit"
	MatchLimitOne              Constant = "kSecMatchLimitOne"
	MatchLimitAll              Constant = "kSecMatchLimitAll"

	// Return Type Key Constants
	ReturnData          Key = "kSecReturnData"
	ReturnAttributes    Key = "kSecReturnAttributes"
	ReturnRef           Key = "kSecReturnRef"
	ReturnPersistentRef Key = "kSecReturnPersistentRef"

	// Value Type Key Constants
	ValueData          Key = "kSecValueData"
	ValueRef           Key = "kSecValueRef"
	ValuePersistentRef Key = "kSecValuePersistentRef"

	// Other Constants
	UseItemList Key = "kSecUseItemList"
	UseKeychain Key = "kSecUseKeychain"

	// UseOperationPrompt is kSecUseOperationPrompt.
	//
	// Deprecated: Use kSecUseAuthenticationContext and set LAContext.localizedReason property
	UseOperationPrompt Key = "kSecUseOperationPrompt"

	// UseNoAuthenticationUI is kSecUseNoAuthenticationUI.
	//
	// Deprecated: Use kSecUseAuthenticationUI instead.
	UseNoAuthenticationUI Key = "kSecUseNoAuthenticationUI"

	UseAuthenticationUI       Key = "kSecUseAuthenticationUI"
	UseAuthenticationContext  Key = "kSecUseAuthenticationContext"
	UseDataProtectionKeychain Key = "kSecUseDataProtectionKeychain"

	// kSecUseAuthenticationUI Value Constants

	// UseAuthenticationUIAllow is kSecUseAuthenticationUIAllow.
	//
	// Deprecated: Instead of kSecUseAuthenticationUI, use kSecUseAuthenticationContext and set LAContext.interactionNotAllowed property
	UseAuthenticationUIAllow Constant = "kSecUseAuthenticationUIAllow"

	// UseAuthenticationUIFail is kSecUseAuthenticationUIFail.
	//
	// Deprecated: Instead of kSecUseAuthenticationUI, use kSecUseAuthenticationContext and set LAContext.interactionNotAllowed property
	UseAuthenticationUIFail Constant = "kSecUseAuthenticationUIFail"

	UseAuthenticationUISkip Constant = "kSecUseAuthenticationUISkip"

	// kSecAttrTokenID Value Constants
	AttrTokenIDSecureEnclave Constant = "kSecAttrTokenIDSecureEnclave"

	// kSecAttrAccessGroup Value Constants
	AttrAccessGroupToken Constant = "kSecAttrAccessGroupToken"
)
